### ISSUE TITLE
When one template throws an exception during initialization, all templates in schedule do not display

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/common-template#113]
**Description**
When one template throws an exception during initialization, all templates in schedule do not display.

**Expected Behaviour**
If a template throws an exception, all other templates in a schedule display as expected and the problematic template is skipped. 

**Actual Behaviour**
All templates do not display when one throws an exception. The breaking point is in the `sendComponentsReadyEvent` function. When this function fails, then `RisePlayerConfiguration.dispatchWindowEvent( "rise-components-ready" );` is not executed. 

**Steps to recreate**

- Stage a template with an intended error during initialization that will throw an exception. 
- Add this template to a schedule among other templates
- Test on a display

**Comment by olegrise** [comment]
Turned out this is not an issue and that this issue was https://github.com/Rise-Vision/rise-embedded-template/issues/17 which is now fixes. 

This issue however inspired us to make an improvement and log the template exceptions into  BQ for better visibility.
