### ISSUE TITLE
Remove legacy logging to client-side-events

### ISSUE THREAD

**Issue by alexey-rise** [Rise-Vision/common-template#158]
Templates should only log information to the new event logs/heartbeats, all legacy logging needs to be removed.

This should only be done on or after 15-Apr-2021

**Comment by alanclayton** [comment]
@stulees this shouldn't be done until https://github.com/Rise-Vision/bq-endpoint-logger/issues/14 is resolved.

**Comment by stulees** [comment]
Closed with #203
