### ISSUE TITLE
Console JSON errors for financial templates.

### ISSUE THREAD

**Issue by RowanDarlison** [Rise-Vision/common-template#68]
Several JSON errors found in the console for the company below when looking at any financial template in the app. See the attached image.
https://apps.risevision.com/templates/edit/42e96a25-3445-4475-845c-ac72525daad9/?cid=2671ad42-0609-41c8-af42-b753493df5e7

There are 5 places where JSON.parse is being used in common template:
https://github.com/Rise-Vision/common-template/blob/master/src/rise-preview.js#L10
https://github.com/Rise-Vision/common-template/blob/master/src/rise-logger.js#L100
https://github.com/Rise-Vision/common-template/blob/master/src/rise-logger.js#L129
https://github.com/Rise-Vision/common-template/blob/master/src/rise-logger.js#L272
https://github.com/Rise-Vision/common-template/blob/master/src/rise-helpers.js#L121

![Screen Shot 2019-06-28 at 11 07 20 AM](https://user-images.githubusercontent.com/12125461/60362209-53c09500-99ae-11e9-8abf-feefcda3dceb.png) 
@santiagonoguez

**Comment by andrecardoso** [comment]
@RowanDarlison I'm not seeing these errors when I open the linked presentation or any other financial template in this company. Could you please confirm if the issue is still occurring? Thanks.
