### ISSUE TITLE
Watch module is logging "data file read error" for certain Displays

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-template#83]
There are a few Displays affected by this. In the past day, 3 Displays logged errors with `display.json`, and one with `attribute-data.json`. Yesterday there were Displays with the same issue but some of them seem to have recovered.

The file contents seem to be empty, as per the error details:
`"stack":"Error: SyntaxError: Unexpected end of JSON input\n at JSON.parse (<anonymous>)\n at https://widgets.risevision.com/stable/common/common-template.min.js:1:8627\nContent: "}`

**Comment by santiagonoguez** [comment]
The displays with repeated logs are corrected now, related issue 811 is still open.
